volumes:
  data:

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pg_scripts:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 55001:5432
    restart: "always"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_USER=user
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  myapp:
    build: .
    depends_on:
      - postgres
      - pgadmin
      - rabbitmq
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'